spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/springboot?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
    type: org.apache.commons.dbcp.BasicDataSource
    initialSize: 10
    maxActive: 100
    minIdle: 5
    maxWait: 50000
